openapi: 3.0.1
info:
  title: Sriwijaya Air REST Web Services
  version: 1.0.0
  description: >-
    Sriwijaya Air REST Web Services is a REST Style web service version 
    from Sriwijaya SOAP Web Services version 111.
  contact:
    name: OpenAPI Collection Team
    url: https://github.com/OpenAPICollection
    email: main@example.com
  license:
    name: OpenAPI Collection Team
    url: https://github.com/OpenAPICollection
servers:
  - url: '{scheme}://api.example.com/{basePath}'
    description: Production Server
    variables:
      scheme:
        description: The API is accessible via https and http
        enum:
          - 'https'
          - 'http'
        default: 'https'
      basePath:
        description: Base path
        enum:
          - 'v1.0'
        default: 'v1.0'
  - url: '{scheme}://api-sandbox.example.com/{basePath}'
    description: Sandbox Server
    variables:
      scheme:
        description: The API is accessible via https and http
        enum:
          - 'https'
          - 'http'
        default: 'https'
      basePath:
        description: Base path
        enum:
          - 'v1.0'
        default: 'v1.0'
tags:
  - name: BookingMgt
    description: Booking Management Features
  - name: AccountMgt
    description: Account Management Features
  - name: ReferenceData
    description: All about data references
paths:
  /BookMgt/WsSearchFlight:
    post:
      tags:
        - BookingMgt
      operationId: bookMgt.WsSearchFlight
      summary: List available flight schedule based on search parameters.
      responses:
        '200':
          description: Return
          content:
            application/json: {}
        '400':
          description: Return with error
          content:
            application/json: {}
        '500':
          description: Return with error
          content:
            application/json: {}
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WsSearchFlightReq'
        required: true
  /BookMgt/WsGeneratePNR:
    post:
      tags:
        - BookingMgt
      operationId: bookMgt.WsGeneratePNR
      summary: Make a booking
      responses:
        '200':
          description: Return
          content:
            application/json: {}
        '400':
          description: Return with error
          content:
            application/json: {}
        '500':
          description: Return with error
          content:
            application/json: {}
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WsGeneratePNRReq'
        required: true
  /BookMgt/WsIssuing:
    post:
      tags:
        - BookingMgt
      operationId: bookMgt.WsIssuing
      summary: Make a booking
      responses:
        '200':
          description: Return
          content:
            application/json: {}
        '400':
          description: Return with error
          content:
            application/json: {}
        '500':
          description: Return with error
          content:
            application/json: {}
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WsIssuingReq'
        required: true
  /BookMgt/WsRetrievePNR:
    post:
      tags:
        - BookingMgt
      operationId: bookMgt.WsRetrievePNR
      summary: Retrieve PNR information
      responses:
        '200':
          description: Return
          content:
            application/json: {}
        '400':
          description: Return with error
          content:
            application/json: {}
        '500':
          description: Return with error
          content:
            application/json: {}
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WsRetrievePNRReq'
        required: true
  /BookMgt/WsCancelPNR:
    post:
      tags:
        - BookingMgt
      operationId: bookMgt.WsCancelPNR
      summary: Cancel active PNR
      responses:
        '200':
          description: Return
          content:
            application/json: {}
        '400':
          description: Return with error
          content:
            application/json: {}
        '500':
          description: Return with error
          content:
            application/json: {}
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WsCancelPNRReq'
        required: true
  /AccountMgt/WsAccountStatement:
    post:
      tags:
        - AccountMgt
      operationId: accountMgt.WsAccountStatement
      summary: Retrieve account statement information
      responses:
        '200':
          description: Return
          content:
            application/json: {}
        '400':
          description: Return with error
          content:
            application/json: {}
        '500':
          description: Return with error
          content:
            application/json: {}
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WsAccountStatementReq'
        required: true
  /AccountMgt/WsCreditBalance:
    post:
      tags:
        - AccountMgt
      operationId: accountMgt.WsCreditBalance
      summary: Retrieve credit balance information
      responses:
        '200':
          description: Return
          content:
            application/json: {}
        '400':
          description: Return with error
          content:
            application/json: {}
        '500':
          description: Return with error
          content:
            application/json: {}
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WsCreditBalanceReq'
        required: true
  /ReferenceData/WsRouteOperate:
    post:
      tags:
        - ReferenceData
      operationId: referenceData.WsRouteOperate
      summary: Retrieve list of route operation
      responses:
        '200':
          description: Return
          content:
            application/json: {}
        '400':
          description: Return with error
          content:
            application/json: {}
        '500':
          description: Return with error
          content:
            application/json: {}
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WsRouteOperateReq'
        required: true
components:
  schemas:
    WsSearchFlightReq:
      type: object
      description: Search Flight Request (WsSearchFlightRequest)
      properties:
        userName:
          $ref: '#/components/schemas/fieldUserName'
        password:
          $ref: '#/components/schemas/fieldPassword'
    WsSearchFlightResp:
      type: object
      description: Search Flight Response (WsSearchFlightResponse)
    WsGeneratePNRReq:
      type: object
      description: Generete PNR/Booking Flight Request (WsGeneratePNRRequest)
      properties:
        userName:
          $ref: '#/components/schemas/fieldUserName'
        password:
          $ref: '#/components/schemas/fieldPassword'
    WsGeneratePNRResp:
      type: object
      description: Generate PNR/Booking Flight Response (WsGeneratePNRResponse)
    WsIssuingReq:
      type: object
      description: Issuing Active PNR Request (WsIssuingRequest)
      properties:
        userName:
          $ref: '#/components/schemas/fieldUserName'
        password:
          $ref: '#/components/schemas/fieldPassword'
    WsIssuingResp:
      type: object
      description: Issuging Active PNR Response (WsIssuingResponse)
    WsCancelPNRReq:
      type: object
      description: Cancel Active PNR Request (WsCancelPNRRequest)
      properties:
        userName:
          $ref: '#/components/schemas/fieldUserName'
        password:
          $ref: '#/components/schemas/fieldPassword'
    WsCancelPNRResp:
      type: object
      description: Cancel Active PNR Response (WsCancelPNRResponse)
    WsAccountStatementReq:
      type: object
      description: Account Statement Request (WsAccountStatementRequest)
      properties:
        userName:
          $ref: '#/components/schemas/fieldUserName'
        password:
          $ref: '#/components/schemas/fieldPassword'
    WsAccountStatementResp:
      type: object
      description: Account Statement Response (WsAccountStatementResponse)
    WsCreditBalanceReq:
      type: object
      description: Credit Balance Request (WsCreditBalanceRequest)
      properties:
        userName:
          $ref: '#/components/schemas/fieldUserName'
        password:
          $ref: '#/components/schemas/fieldPassword'
    WsCreditBalanceResp:
      type: object
      description: Credit Balance Response (WsCreditBalanceResponse)
    WsRouteOperateReq:
      type: object
      description: Route Operate Request (WsRouteOperateRequest)
      properties:
        userName:
          $ref: '#/components/schemas/fieldUserName'
        password:
          $ref: '#/components/schemas/fieldPassword'
    WsRouteOperateResp:
      type: object
      description: Route Operate Response (WsRouteOperateResponse)
    fieldUserName:
      type: string
      description: Sriwijaya Agent Username
      example: SRIWIJAYA_AGENT_USER_NAME
    fieldPassword:
      type: string
      description: Sriwijaya Agent Password
      example: SRIWIJAYA_AGENT_PASSWORD  
  parameters: {}
externalDocs:
  description: Find out more about Sriwijaya Air REST Web Services
  url: 'https://github.com/OpenAPICollection/sriwijaya-ws-openapi'
