openapi: 3.0.1
info:
  title: Sriwijaya Air REST Web Services
  version: 1.0.0
  description: >-
    Sriwijaya Air REST Web Services is a REST Style web service version 
    from Sriwijaya SOAP Web Services version 111.
  contact:
    name: OpenAPI Collection Team
    url: https://github.com/OpenAPICollection
    email: main@example.com
  license:
    name: OpenAPI Collection Team
    url: https://github.com/OpenAPICollection
servers:
  - url: '{scheme}://api.example.com/{basePath}'
    description: Production Server
    variables:
      scheme:
        description: The API is accessible via https and http
        enum:
          - 'https'
          - 'http'
        default: 'https'
      basePath:
        description: Base path
        enum:
          - 'v1.0'
        default: 'v1.0'
  - url: '{scheme}://api-sandbox.example.com/{basePath}'
    description: Sandbox Server
    variables:
      scheme:
        description: The API is accessible via https and http
        enum:
          - 'https'
          - 'http'
        default: 'https'
      basePath:
        description: Base path
        enum:
          - 'v1.0'
        default: 'v1.0'
tags:
  - name: BookingMgt
    description: Booking Management Features
  - name: AccountMgt
    description: Account Management Features
  - name: ReferenceData
    description: All about data references
paths:
  /BookMgt/WsSearchFlight:
    post:
      tags:
        - BookingMgt
      operationId: bookMgt.WsSearchFlight
      summary: List available flight schedule based on search parameters.
      responses:
        '200':
          description: Return
          content:
            application/json: {}
        '400':
          description: Return with error
          content:
            application/json: {}
        '500':
          description: Return with error
          content:
            application/json: {}
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WsSearchFlightReq'
        required: true
  /BookMgt/WsGeneratePNR:
    post:
      tags:
        - BookingMgt
      operationId: bookMgt.WsGeneratePNR
      summary: Make a booking
      responses:
        '200':
          description: Return
          content:
            application/json: {}
        '400':
          description: Return with error
          content:
            application/json: {}
        '500':
          description: Return with error
          content:
            application/json: {}
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WsGeneratePNRReq'
        required: true
  /BookMgt/WsIssuing:
    post:
      tags:
        - BookingMgt
      operationId: bookMgt.WsIssuing
      summary: Make a booking
      responses:
        '200':
          description: Return
          content:
            application/json: {}
        '400':
          description: Return with error
          content:
            application/json: {}
        '500':
          description: Return with error
          content:
            application/json: {}
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WsIssuingReq'
        required: true
  /BookMgt/WsRetrievePNR:
    post:
      tags:
        - BookingMgt
      operationId: bookMgt.WsRetrievePNR
      summary: Retrieve PNR information
      responses:
        '200':
          description: Return
          content:
            application/json: {}
        '400':
          description: Return with error
          content:
            application/json: {}
        '500':
          description: Return with error
          content:
            application/json: {}
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WsRetrievePNRReq'
        required: true
  /BookMgt/WsCancelPNR:
    post:
      tags:
        - BookingMgt
      operationId: bookMgt.WsCancelPNR
      summary: Cancel active PNR
      responses:
        '200':
          description: Return
          content:
            application/json: {}
        '400':
          description: Return with error
          content:
            application/json: {}
        '500':
          description: Return with error
          content:
            application/json: {}
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WsCancelPNRReq'
        required: true
  /AccountMgt/WsAccountStatement:
    post:
      tags:
        - AccountMgt
      operationId: accountMgt.WsAccountStatement
      summary: Retrieve account statement information
      responses:
        '200':
          description: Return
          content:
            application/json: {}
        '400':
          description: Return with error
          content:
            application/json: {}
        '500':
          description: Return with error
          content:
            application/json: {}
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WsAccountStatementReq'
        required: true
  /AccountMgt/WsCreditBalance:
    post:
      tags:
        - AccountMgt
      operationId: accountMgt.WsCreditBalance
      summary: Retrieve credit balance information
      responses:
        '200':
          description: Return
          content:
            application/json: {}
        '400':
          description: Return with error
          content:
            application/json: {}
        '500':
          description: Return with error
          content:
            application/json: {}
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WsCreditBalanceReq'
        required: true
  /ReferenceData/WsRouteOperate:
    post:
      tags:
        - ReferenceData
      operationId: referenceData.WsRouteOperate
      summary: Retrieve list of route operation
      responses:
        '200':
          description: Return
          content:
            application/json: {}
        '400':
          description: Return with error
          content:
            application/json: {}
        '500':
          description: Return with error
          content:
            application/json: {}
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WsRouteOperateReq'
        required: true
components:
  schemas:
    WsSearchFlightReq:
      type: object
      description: Search Flight Request (WsSearchFlightRequest)
      properties:
        userName:
          $ref: '#/components/schemas/fieldUserName'
        password:
          $ref: '#/components/schemas/fieldPassword'
        cityFrom:
          $ref: '#/components/schemas/fieldCityFrom'
        cityTo:
          $ref: '#/components/schemas/fieldCityTo'
        returnStatus:
          $ref: '#/components/schemas/fieldReturnStatus'
        departDate:
          $ref: '#/components/schemas/fieldDepartDate'
        returnDate:
          $ref: '#/components/schemas/fieldReturnDate'
        promoCode:
          $ref: '#/components/schemas/fieldPromoCode'
        adult:
          $ref: '#/components/schemas/fieldAdult'
        child:
          $ref: '#/components/schemas/fieldChild'
        infant:
          $ref: '#/components/schemas/fieldInfant'
    WsSearchFlightResp:
      type: object
      description: Search Flight Response (WsSearchFlightResponse)
    WsGeneratePNRReq:
      type: object
      description: Generete PNR/Booking Flight Request (WsGeneratePNRRequest)
      properties:
        userName:
          $ref: '#/components/schemas/fieldUserName'
        password:
          $ref: '#/components/schemas/fieldPassword'
        received:
          $ref: '#/components/schemas/fieldReceived'
        receivedPhone:
          $ref: '#/components/schemas/fieldReceivedPhone'
        email:
          $ref: '#/components/schemas/fieldEmail'
        searchKey:
          $ref: '#/components/schemas/fieldSearchKey'
        extraCoverAddOns:
          $ref: '#/components/schemas/fieldExtraCoverAddOns'
        adultPaxNames:
          type: array
          items:
            $ref: '#/components/schemas/ObjectInputReqNames'
        childPaxNames:
          type: array
          items:
            $ref: '#/components/schemas/ObjectInputReqNames'
        infantPaxNames:
          type: array
          items:
            $ref: '#/components/schemas/ObjectInputReqArrayInf'
        keys:
          type: array
          items: 
            $ref: '#/components/schemas/ObjectInputReqArrayKey'
    WsGeneratePNRResp:
      type: object
      description: Generate PNR/Booking Flight Response (WsGeneratePNRResponse)
    WsIssuingReq:
      type: object
      description: Issuing Active PNR Request (WsIssuingRequest)
      properties:
        userName:
          $ref: '#/components/schemas/fieldUserName'
        password:
          $ref: '#/components/schemas/fieldPassword'
        bookingCode:
          $ref: '#/components/schemas/fieldBookingCode'
    WsIssuingResp:
      type: object
      description: Issuging Active PNR Response (WsIssuingResponse)
    WsRetrievePNRReq:
      type: object
      description: Retrieve PNR Request (WsRetrievePNRReq)
      properties:
        userName:
          $ref: '#/components/schemas/fieldUserName'
        password:
          $ref: '#/components/schemas/fieldPassword'
        bookingCode:
          $ref: '#/components/schemas/fieldBookingCode'
    WsRetrievePNRResp:
      type: object
      description: Retrieve PNR Request (WsRetrievePNRResp)
    WsCancelPNRReq:
      type: object
      description: Cancel Active PNR Request (WsCancelPNRRequest)
      properties:
        userName:
          $ref: '#/components/schemas/fieldUserName'
        password:
          $ref: '#/components/schemas/fieldPassword'
        bookingCode:
          $ref: '#/components/schemas/fieldBookingCode'
    WsCancelPNRResp:
      type: object
      description: Cancel Active PNR Response (WsCancelPNRResponse)
    WsAccountStatementReq:
      type: object
      description: Account Statement Request (WsAccountStatementRequest)
      properties:
        userName:
          $ref: '#/components/schemas/fieldUserName'
        password:
          $ref: '#/components/schemas/fieldPassword'
        periodeStart:
          type: string
          description: Periode Start (DD-Mmm-YY)
          example: '01-Sep-18'
        periodeEnd:
          type: string
          description: Periode End (DD-Mmm-YY)
          example: '02-Sep-18'
    WsAccountStatementResp:
      type: object
      description: Account Statement Response (WsAccountStatementResponse)
    WsCreditBalanceReq:
      type: object
      description: Credit Balance Request (WsCreditBalanceRequest)
      properties:
        userName:
          $ref: '#/components/schemas/fieldUserName'
        password:
          $ref: '#/components/schemas/fieldPassword'
    WsCreditBalanceResp:
      type: object
      description: Credit Balance Response (WsCreditBalanceResponse)
    WsRouteOperateReq:
      type: object
      description: Route Operate Request (WsRouteOperateRequest)
      properties:
        userName:
          $ref: '#/components/schemas/fieldUserName'
        password:
          $ref: '#/components/schemas/fieldPassword'
    WsRouteOperateResp:
      type: object
      description: Route Operate Response (WsRouteOperateResponse)
    ObjectInputReqNames:
      type: object
      properties:
        firstName:
          $ref: '#/components/schemas/fieldFirstName'
        lastName:
          $ref: '#/components/schemas/fieldLastName'
        suffix:
          $ref: '#/components/schemas/fieldSuffix'
        doB:
          $ref: '#/components/schemas/fieldDoB'
        idNo:
          $ref: '#/components/schemas/fieldIdNo'
    ObjectInputReqArrayInf:
      type: object
      properties:
        firstName:
          $ref: '#/components/schemas/fieldFirstName'
        lastName:
          $ref: '#/components/schemas/fieldLastName'
        suffix:
          $ref: '#/components/schemas/fieldSuffix'
        doB:
          $ref: '#/components/schemas/fieldDoB'
        adultRefference:
          $ref: '#/components/schemas/fieldAdultRefference'
        idNo:
          $ref: '#/components/schemas/fieldIdNo'
    ObjectInputReqArrayKey:
      type: object
      properties:
        key:
          type: string
          description: Selected Segment Class Key
          example: 10962952:Y:S
        category:
          type: string
          description: Category
          enum:
            - Departure
            - Return
          default: Departure
    fieldUserName:
      type: string
      description: Sriwijaya Agent Username
      example: SRIWIJAYA_AGENT_USER_NAME
    fieldPassword:
      type: string
      description: Sriwijaya Agent Password
      example: SRIWIJAYA_AGENT_PASSWORD  
    fieldBookingCode:
      type: string
      description: Booking Code/PNR Code
      example: ABMNYZ
    fieldReturnStatus: 
      type: string
      description: Return Status On Search Flight
      enum:
        - 'NO'
        - 'YES'
      default: 'YES'
    fieldCityFrom:
      type: string
      description: City Source Location
      example: CGK
    fieldCityTo:
      type: string
      description: City Destination Location
      example: DPS
    fieldDepartDate:
      type: string
      description: Departure Date (DD-Mmm-YY)
      example: '01-Sep-18'
    fieldReturnDate:
      type: string
      description: Return Date (DD-Mmm-YY)
      example: '05-Sep-18'
    fieldPromoCode:
      type: string
      description: Promotion Code
      example: XXX10
    fieldAdult:
      type: integer
      description: Adult Pax Count
      example: 1
    fieldChild:
      type: integer
      description: Child Pax Count
      example: 1
    fieldInfant:
      type: integer
      description: Infant Pax Count
      example: 1
    fieldReceived:
      type: string
      description: Contact Name
      example: ANGKASA SRIWIJAYA
    fieldReceivedPhone:
      type: string
      description: Contact Phone Number
      example: 08123321123
    fieldEmail:
      type: string
      description: Contact Email
      example: angkasa.sriwijaya@gmail.com
    fieldSearchKey:
      type: string
      description: Search Key Response from Search Flight
      example: 050090414591759173467946474365644449444669467547
    fieldExtraCoverAddOns:
      type: string
      description: Extra Cover Add Ons (STI, etc.)
      enum:
        - NO
        - YES
      default: NO
    fieldFirstName: 
      type: string
      description: First Name
    fieldLastName: 
      type: string
      description: Last Name
    fieldSuffix: 
      type: string
      description: Suffix Name
      enum:
        - 'Mr'
        - 'Mrs'
        - 'Ms'
        - 'Mstr'
        - 'Miss'
      default:  'Mr'   
    fieldDoB:
      type: string
      description: Date of Birth (YYYY-MM-DD)
      example: '2009-09-09'
    fieldIdNo:
      type: string
      description: Pax Identification Number (Passport, SSN, Driver license, etc.)
      example: A-11223344
    fieldAdultRefference:
      type: integer
      description: Adult Refference 
      example: 1
  parameters: {}
externalDocs:
  description: Find out more about Sriwijaya Air REST Web Services
  url: 'https://github.com/OpenAPICollection/sriwijaya-ws-openapi'
